import Head from 'next/head';
import { useEffect, useState } from 'react';
import { useRecoilState } from 'recoil';

import { billState, peopleState, tipPercentState } from '../atoms/inputAtoms';
import Bill from '../components/Bill';
import People from '../components/People';
import Results from '../components/Results';
import Tips from '../components/Tips';

export default function Home() {
  const [bill, setBill] = useRecoilState(billState)
  const [people, setPeople] = useRecoilState(peopleState)
  const [tipPercent, setTipPercent] = useRecoilState(tipPercentState)

  const billFloat = parseFloat(bill)
  const peopleFloat = parseFloat(people)
  const tipPercentFloat = parseFloat(tipPercent)

  console.log(billFloat, tipPercentFloat, peopleFloat)

  return (
    <div className='flex justify-center min-h-screen border-2 border-red-300'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col items-center justify-center m-5 border-4 border-red-500 rounded-2xl '>
        <header className='tracking-[.4em] text-2xl font-semibold opacity-70 m-6'>
          <h1>
            SPLI
            <br />
            TTER
          </h1>
        </header>

        <main className='h-full bg-white rounded-3xl w-96'>
          <div className='mx-6 my-8'>
            <Bill bill={bill} />
            <Tips tip={tipPercent} />
            <People people={people} />
            <Results />
          </div>
        </main>
      </main>
    </div>
  )
}
